### ISSUE TITLE
Re-renders seem to be broken

### ISSUE THREAD

**Issue by creatorrr** [andrelandgraf/react-ssml-dom#1]
Hey @andrelandgraf ,

Not sure if I missed something but re-renders seem to be broken. After the initial render finishes (which works perfectly) and the `Document` has been updated, any subsequent updates are not reflected on the document like `Suspense` or changes made from within `useEffect` calls etc. 

Is this a known bug or the result of a common mistake? If something needs fixing, I would be happy to raise a PR if you point me in the right direction. :)

**Comment by andrelandgraf** [comment]
Hey @creatorrr,

Cool seeing folks playing around with this project!

This is very much a research project. The code you are seeing in the `/demo` folder might be broken. I was just playing around with `Suspense` for data fetching myself.

Also, keep in mind that the code runs server-side. Usually, in a server environment you only render your React app once. `useEffect` is never triggered on server-side renders. At least that's the common practice for most SSR frameworks like Next.js or Remix.run. I actually had [an older version of this code](https://github.com/andrelandgraf/react-ssml-dom/tree/eb446b655aa919ea67ae6d3e9e71e4b98a925958) where I made the app render several times on the server to allow `useEffect` to be used, but that was also just a research project!

Hope this helps!

**Comment by creatorrr** [comment]
Thanks @andrelandgraf ! That makes sense, I'll keep playing around with it and let you know. Closing this issue for now :)
